accum_steps: 2
batch_size: 12
devices: '1'
eval_path: ../docgen_export/docgen_export_valid.jsonl
eval_steps: 1000
experiment_name: proofGPT-1.3B
gradient_clipping: 1.0
logging_steps: 500
lr: 5.0e-05
max_length: 400
model_name: EleutherAI/pythia-1.3b
save_steps: 5000
train_path: ../docgen_export/docgen_export_train.jsonl
train_steps: 20000
warmup_steps: 2000
weight_decay: 0.01
