accum_steps: 4
batch_size: 6
devices: '1'
eval_path: ../finetune_data/v2_finetune_valid.jsonl
eval_steps: 1000
experiment_name: gptneo1B_train
gradient_clipping: 1.0
logging_steps: 500
lr: 5.0e-05
max_length: 450
model_name: EleutherAI/gpt-neo-1.3B
save_steps: 5000
train_path: ../finetune_data/v2_finetune.jsonl
train_steps: 10000
warmup_steps: 1000
weight_decay: 0.01
