model: "../train_backtranslation/local_finetune/runs/proofGPT-1.3B-backtranslation/checkpoint-15000"
hfmodel: "hoskinson-center/proofGPT-v0.1"
batch_size: 1
in_key: "nl_statement"
out_key: "gpt_formal_statement"
ref_key: "formal_statement"
save_dir: "results/toy_proofgpt_backtranslate"
save_file: "out.jsonl"
max_tokens: 350
split: "test"

