hfmodel: "hoskinson-center/proofGPT-v0.1"
batch_size: 1
before_example: "\nLean mathlib version:\n"
after_example: "\nTranslate the Lean mathlib version to a natural language version: \""
in_key: "formal_statement"
out_key: "gpt_nl_statement"
ref_key: "nl_statement"
save_dir: "results/proofgpt-1.3b_6shot_informalize"
save_file: "out.jsonl"
few_shot_prompt_path: "prompts/6shot_informalize.txt"
stop: "\""
max_tokens: 275
split: "test"
