model_name: "../informalization/local_finetune/runs/proofGPT-1.3B/checkpoint-20000"
tokenizer_name: "hoskinson-center/proofGPT-v0.1"
batch_size: 1
in_key: "nl_statement"
out_key: "gpt_formal_statement"
ref_key: "formal_statement"
save_dir: "results/proofgpt_formalize"
save_file: "out.jsonl"
data_path: "workshop_model_input.jsonl"
max_tokens: 350
split: "test"

